project_id = "awdysfgjmhnqwsoyhbah"

[functions.run-security-checks]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.scheduled-scan]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.ping-website]
verify_jwt = false