/* ─── Compliance Framework Definitions ─── */

export interface FrameworkControl {
  code: string;
  title: string;
  domain: string;
  type: 'auto' | 'manual' | 'hybrid';
  description: string;
  requirements: string;
  recommendations: string[];
}

export interface ComplianceFramework {
  key: string;
  name: string;
  domains: string[];
  controls: FrameworkControl[];
}

/* ═══════════════════════════════════════════════
   CIS Controls v8
   ═══════════════════════════════════════════════ */
const CIS_CONTROLS: FrameworkControl[] = [
  { code: 'CIS-1.1', title: 'Enterprise Asset Inventory', domain: 'Identity', type: 'hybrid',
    description: 'Actively manage all enterprise assets connected to the infrastructure',
    requirements: 'Establish and maintain an accurate, detailed, and up-to-date inventory of all enterprise assets with the potential to store or process data. This includes end-user devices, network devices, IoT devices, and servers.',
    recommendations: ['Use automated tools for asset discovery and inventory management', 'Update asset inventory at least weekly', 'Include cloud-hosted and remote assets', 'Track asset ownership and business criticality'] },
  { code: 'CIS-2.1', title: 'Software Asset Inventory', domain: 'Endpoint', type: 'hybrid',
    description: 'Actively manage all software on the network',
    requirements: 'Establish and maintain a detailed inventory of all licensed and authorized software installed on enterprise assets. The software inventory must document the title, publisher, initial install/use date, and business purpose.',
    recommendations: ['Deploy software inventory tools across all endpoints', 'Maintain an approved software whitelist', 'Audit software inventory monthly', 'Remove unauthorized or end-of-life software'] },
  { code: 'CIS-3.1', title: 'Data Protection', domain: 'Data', type: 'manual',
    description: 'Establish processes for data management',
    requirements: 'Establish and maintain a data management process that addresses data sensitivity, data owner, handling of data, data retention limits, and disposal requirements.',
    recommendations: ['Classify all data by sensitivity level', 'Document data flows and storage locations', 'Implement data retention and disposal policies', 'Train staff on data handling procedures'] },
  { code: 'CIS-3.10', title: 'Encrypt Data in Transit', domain: 'Data', type: 'auto',
    description: 'Encrypt data in transit using strong cryptographic protocols',
    requirements: 'Encrypt data in transit using strong cryptographic protocols (TLS 1.2+). Enforce HTTPS for all web-facing services and ensure HSTS headers are deployed to prevent downgrade attacks.',
    recommendations: ['Enable TLS 1.2 or higher on all services', 'Deploy HSTS headers with a minimum 1-year max-age', 'Disable older protocols (SSLv3, TLS 1.0/1.1)', 'Use automated certificate management for timely renewals'] },
  { code: 'CIS-4.1', title: 'Secure Configuration (Endpoints)', domain: 'Network', type: 'auto',
    description: 'Establish secure configuration processes for enterprise assets',
    requirements: 'Establish and maintain a secure configuration process for enterprise assets (end-user devices, servers, network devices) and software. Review and update documentation annually or when significant changes occur.',
    recommendations: ['Use CIS Benchmarks or DISA STIGs as configuration baselines', 'Automate configuration deployment with infrastructure-as-code', 'Implement security headers (CSP, X-Frame-Options, X-Content-Type-Options)', 'Reduce attack surface by closing unnecessary ports'] },
  { code: 'CIS-4.2', title: 'Secure Configuration (Network)', domain: 'Network', type: 'auto',
    description: 'Establish secure network infrastructure configuration',
    requirements: 'Establish and maintain a secure configuration process for network infrastructure, including firewalls, routers, switches, and wireless access points. Implement network segmentation and traffic filtering.',
    recommendations: ['Deploy a Web Application Firewall (WAF)', 'Use a CDN for DDoS mitigation', 'Enable rate limiting on all public endpoints', 'Segment networks to isolate critical assets'] },
  { code: 'CIS-5.1', title: 'Account Management', domain: 'Identity', type: 'manual',
    description: 'Establish and maintain an inventory of all accounts',
    requirements: 'Establish and maintain an inventory of all accounts managed in the enterprise including end-user, administrative, service, and application accounts.',
    recommendations: ['Implement centralized identity management', 'Enforce MFA for all privileged accounts', 'Review account access quarterly', 'Disable dormant accounts after 45 days'] },
  { code: 'CIS-6.1', title: 'Access Management', domain: 'Identity', type: 'manual',
    description: 'Establish and maintain an access management process',
    requirements: 'Establish and maintain an access management process for granting, reviewing, and revoking access to enterprise assets and software, based on the principle of least privilege.',
    recommendations: ['Implement role-based access control (RBAC)', 'Conduct access reviews at least quarterly', 'Automate provisioning and deprovisioning', 'Enforce separation of duties for critical functions'] },
  { code: 'CIS-7.1', title: 'Vulnerability Management', domain: 'Endpoint', type: 'auto',
    description: 'Establish and maintain a vulnerability management process',
    requirements: 'Establish and maintain a documented vulnerability management process for enterprise assets. Review and update documentation annually or when significant enterprise changes occur.',
    recommendations: ['Run vulnerability scans at least monthly', 'Prioritize patching by CVSS score and exploitability', 'Remediate critical vulnerabilities within 14 days', 'Track and report on patch compliance metrics'] },
  { code: 'CIS-8.1', title: 'Audit Log Management', domain: 'IR', type: 'manual',
    description: 'Establish and maintain an audit log management process',
    requirements: 'Establish and maintain an audit log management process that defines logging requirements, review cadence, and retention period for enterprise assets.',
    recommendations: ['Enable audit logging on all critical systems', 'Centralize logs in a SIEM platform', 'Retain logs for at least 90 days online, 1 year archived', 'Review high-severity alerts within 24 hours'] },
  { code: 'CIS-9.1', title: 'Email & Browser Protection', domain: 'App', type: 'manual',
    description: 'Establish email and web browser protections',
    requirements: 'Establish and maintain email and web browser protections to reduce the attack surface and manage human vulnerabilities.',
    recommendations: ['Deploy email filtering with anti-phishing capabilities', 'Implement DMARC, DKIM, and SPF records', 'Use browser isolation for high-risk browsing', 'Block known malicious URLs at the gateway'] },
  { code: 'CIS-10.1', title: 'Malware Defenses', domain: 'Endpoint', type: 'manual',
    description: 'Establish anti-malware protections on all assets',
    requirements: 'Establish and maintain anti-malware software on all enterprise assets, with automatic updates and real-time scanning capabilities.',
    recommendations: ['Deploy EDR/XDR on all endpoints', 'Enable real-time protection and behavioral analysis', 'Ensure signature updates occur at least daily', 'Monitor and respond to malware alerts promptly'] },
  { code: 'CIS-11.1', title: 'Data Recovery', domain: 'Backup', type: 'manual',
    description: 'Establish and maintain a data recovery process',
    requirements: 'Establish and maintain a data recovery process. Include backup scope, frequency, and restoration testing requirements.',
    recommendations: ['Implement automated daily backups for critical data', 'Store backups in geographically separate locations', 'Test backup restoration at least quarterly', 'Encrypt all backup data at rest and in transit'] },
  { code: 'CIS-12.1', title: 'Network Infrastructure Management', domain: 'Network', type: 'auto',
    description: 'Ensure network infrastructure is kept up-to-date',
    requirements: 'Ensure network infrastructure is kept up-to-date. Use supported and patched versions of all network operating systems, firmware, and components.',
    recommendations: ['Maintain a current inventory of network device firmware versions', 'Subscribe to vendor security advisories', 'Apply critical patches within 30 days of release', 'Replace end-of-life hardware and software'] },
  { code: 'CIS-13.1', title: 'Security Monitoring & Alerting', domain: 'IR', type: 'auto',
    description: 'Centralize security event alerting across assets',
    requirements: 'Centralize security event alerting across enterprise assets for log correlation and analysis. Integrate all critical monitoring systems into a unified alerting framework.',
    recommendations: ['Integrate uptime, SSL, DDoS, and threat monitoring feeds', 'Define escalation procedures for critical alerts', 'Implement correlation rules to reduce false positives', 'Ensure 24/7 coverage for high-severity alerts'] },
  { code: 'CIS-14.1', title: 'Security Awareness Training', domain: 'Identity', type: 'manual',
    description: 'Establish a security awareness program',
    requirements: 'Establish and maintain a security awareness and training program. Ensure all workforce members receive appropriate training upon hire and annually thereafter.',
    recommendations: ['Conduct phishing simulations at least quarterly', 'Track training completion rates', 'Customize training for role-specific risks', 'Include incident reporting procedures in training'] },
  { code: 'CIS-15.1', title: 'Service Provider Management', domain: 'Network', type: 'manual',
    description: 'Manage service providers that handle enterprise data',
    requirements: "Establish and maintain an inventory of service providers that process, store, or transmit enterprise data. Assess each provider's security posture.",
    recommendations: ['Maintain a vendor risk register', 'Require SOC 2 or ISO 27001 from critical vendors', 'Review vendor security annually', 'Include security requirements in all contracts'] },
  { code: 'CIS-16.1', title: 'Application Software Security', domain: 'App', type: 'auto',
    description: 'Deploy security headers on all web applications',
    requirements: 'Establish and maintain a secure application development process. Deploy security headers (CSP, X-Frame-Options, X-Content-Type-Options) on all web applications.',
    recommendations: ['Implement Content Security Policy (CSP) headers', 'Deploy X-Frame-Options to prevent clickjacking', 'Set X-Content-Type-Options: nosniff', 'Conduct regular application security testing (SAST/DAST)'] },
  { code: 'CIS-16.11', title: 'Database Hardening', domain: 'App', type: 'auto',
    description: 'Harden database servers to prevent unauthorized access',
    requirements: 'Harden database servers to prevent unauthorized access. Ensure database ports (MySQL 3306, PostgreSQL 5432, MongoDB 27017) are not publicly exposed.',
    recommendations: ['Block database ports from public internet access', 'Use encrypted connections for database access', 'Implement database-level access controls', 'Enable database audit logging'] },
  { code: 'CIS-17.1', title: 'Incident Response', domain: 'IR', type: 'manual',
    description: 'Establish and maintain an incident response plan',
    requirements: 'Establish and maintain an incident response plan that addresses roles, responsibilities, communication requirements, and phases of incident response.',
    recommendations: ['Document incident classification and escalation procedures', 'Conduct tabletop exercises at least bi-annually', 'Define communication templates for stakeholders', 'Review and update the plan after each incident'] },
];

/* ═══════════════════════════════════════════════
   NIST Cybersecurity Framework 2.0
   ═══════════════════════════════════════════════ */
const NIST_CONTROLS: FrameworkControl[] = [
  // GOVERN
  { code: 'GV.OC-01', title: 'Organizational Context', domain: 'Govern', type: 'manual',
    description: 'The organizational mission is understood and informs cybersecurity risk management',
    requirements: 'The organizational mission is understood and informs cybersecurity risk management. Organizational context, including mission, stakeholder expectations, and dependencies, is understood and used to inform risk management decisions.',
    recommendations: ['Document organizational mission and its cybersecurity implications', 'Identify key stakeholders and their cybersecurity expectations', 'Map dependencies between business functions and IT systems', 'Integrate cybersecurity into strategic planning'] },
  { code: 'GV.RM-01', title: 'Risk Management Strategy', domain: 'Govern', type: 'hybrid',
    description: 'Risk management objectives are established and communicated',
    requirements: 'Risk management objectives are established and communicated. The organization has established a risk management strategy that includes risk appetite, tolerance, and assumptions used to support operational risk decisions.',
    recommendations: ['Define and document risk appetite and tolerance levels', 'Implement continuous monitoring across all critical assets', 'Communicate risk management objectives to all stakeholders', 'Review risk management strategy annually'] },
  { code: 'GV.SC-01', title: 'Supply Chain Risk Management', domain: 'Govern', type: 'hybrid',
    description: 'Cyber supply chain risk management processes are established',
    requirements: 'Cyber supply chain risk management processes are identified, established, managed, monitored, and improved. Third-party software and service dependencies are documented and assessed.',
    recommendations: ['Inventory all third-party software components', 'Assess vendor security posture regularly', 'Include security requirements in procurement processes', 'Monitor for supply chain compromises'] },
  { code: 'GV.PO-01', title: 'Cybersecurity Policy', domain: 'Govern', type: 'manual',
    description: 'Organizational cybersecurity policy is established and communicated',
    requirements: 'A cybersecurity policy is established based on organizational context and strategy. The policy addresses the security requirements for all stakeholders and is communicated across the organization.',
    recommendations: ['Develop comprehensive cybersecurity policy', 'Ensure policy covers all aspects of operations', 'Review and update policy annually', 'Communicate policy to all employees'] },

  // IDENTIFY
  { code: 'ID.AM-01', title: 'Hardware Asset Inventory', domain: 'Identify', type: 'hybrid',
    description: 'Inventories of hardware managed by the organization are maintained',
    requirements: 'Inventories of hardware managed by the organization are maintained. Asset inventories include complete details (URL, IP, sector) and are kept current for all monitored entities.',
    recommendations: ['Register all assets with complete metadata', 'Include URL, IP address, and sector classification', 'Review asset records for completeness monthly', 'Automate asset discovery where possible'] },
  { code: 'ID.AM-02', title: 'Software Asset Inventory', domain: 'Identify', type: 'auto',
    description: 'Inventories of software managed by the organization are maintained',
    requirements: 'Inventories of software, services, and systems managed by the organization are maintained. Technology stack identification through fingerprinting provides visibility into deployed software.',
    recommendations: ['Run technology fingerprinting scans regularly', 'Document all detected software components', 'Track software versions for currency', 'Identify unauthorized software installations'] },
  { code: 'ID.RA-01', title: 'Vulnerability Identification', domain: 'Identify', type: 'auto',
    description: 'Vulnerabilities in assets are identified, validated, and recorded',
    requirements: 'Vulnerabilities in assets are identified, validated, and recorded. Comprehensive vulnerability scanning covers security headers, open ports, defacement, DNS, and blacklist status.',
    recommendations: ['Conduct regular vulnerability scans across all check types', 'Prioritize remediation by risk severity', 'Track vulnerability remediation timelines', 'Validate fixes after remediation'] },
  { code: 'ID.RA-02', title: 'Threat Intelligence', domain: 'Identify', type: 'auto',
    description: 'Cyber threat intelligence is received from information sharing forums and sources',
    requirements: 'Cyber threat intelligence is received from information sharing forums and sources. The organization consumes threat intelligence feeds to identify potential threats to its assets.',
    recommendations: ['Subscribe to multiple threat intelligence feeds', 'Correlate threat data with organizational assets', 'Share threat intelligence with sector peers', 'Act on actionable threat intelligence promptly'] },
  { code: 'ID.RA-05', title: 'Risk Prioritization', domain: 'Identify', type: 'hybrid',
    description: 'Risks are prioritized based on assessment findings',
    requirements: 'Threats, vulnerabilities, likelihoods, and impacts are used to understand inherent risk and inform risk response prioritization. Security scorecards provide quantitative risk measurement.',
    recommendations: ['Calculate and track security scores for all assets', 'Use risk scores to prioritize remediation', 'Review risk priorities at least monthly', 'Align risk priorities with business impact'] },

  // PROTECT
  { code: 'PR.AC-01', title: 'Identity Management', domain: 'Protect', type: 'manual',
    description: 'Identities and credentials for authorized users are managed',
    requirements: 'Identities and credentials for authorized users, services, and hardware are managed by the organization. Access privileges are established, maintained, and enforced.',
    recommendations: ['Implement centralized identity management', 'Enforce strong authentication for all users', 'Manage service accounts with the same rigor as user accounts', 'Review credentials and access regularly'] },
  { code: 'PR.DS-01', title: 'Data-at-Rest Protection', domain: 'Protect', type: 'manual',
    description: 'Data-at-rest is protected',
    requirements: 'Data-at-rest is protected. Encryption, access controls, and integrity measures protect stored data commensurate with its sensitivity.',
    recommendations: ['Encrypt sensitive data at rest', 'Implement access controls for data storage', 'Monitor for unauthorized data access', 'Use hardware security modules for key management'] },
  { code: 'PR.DS-02', title: 'Data-in-Transit Protection', domain: 'Protect', type: 'auto',
    description: 'Data-in-transit is protected',
    requirements: 'Data-in-transit is protected. Valid SSL/TLS certificates and HSTS headers ensure encrypted communications and prevent downgrade attacks.',
    recommendations: ['Deploy valid SSL/TLS certificates on all services', 'Enable HSTS with appropriate max-age', 'Disable insecure protocols', 'Monitor certificate expiration dates'] },
  { code: 'PR.DS-10', title: 'Data Integrity', domain: 'Protect', type: 'auto',
    description: 'The integrity of data is ensured through content monitoring',
    requirements: 'The confidentiality, integrity, and availability of data-in-use are protected. Content integrity monitoring detects unauthorized modifications such as defacement.',
    recommendations: ['Implement content hash monitoring', 'Set up defacement detection alerts', 'Establish baseline content snapshots', 'Respond to integrity violations immediately'] },
  { code: 'PR.IP-01', title: 'Security Configuration', domain: 'Protect', type: 'auto',
    description: 'Security configuration baselines are established and maintained',
    requirements: 'Configuration baselines for technology assets are established, maintained, and enforced. Security headers and port configurations follow hardening best practices.',
    recommendations: ['Deploy all recommended security headers', 'Close unnecessary ports', 'Follow CIS Benchmarks for configuration', 'Audit configurations regularly'] },
  { code: 'PR.IP-04', title: 'Network Protection', domain: 'Protect', type: 'auto',
    description: 'Network protection mechanisms are implemented',
    requirements: 'Communications and control networks are protected. CDN, WAF, and rate limiting provide layered defense against network-based attacks.',
    recommendations: ['Deploy CDN for DDoS mitigation', 'Implement Web Application Firewall', 'Enable rate limiting on public endpoints', 'Monitor network traffic for anomalies'] },
  { code: 'PR.AT-01', title: 'Awareness & Training', domain: 'Protect', type: 'manual',
    description: 'Personnel are provided cybersecurity awareness and training',
    requirements: 'The organization\'s personnel are provided cybersecurity awareness education and training so they can perform their cybersecurity-related tasks.',
    recommendations: ['Provide role-based security training', 'Conduct regular phishing simulations', 'Update training content annually', 'Track and report training completion rates'] },

  // DETECT
  { code: 'DE.CM-01', title: 'Network Monitoring', domain: 'Detect', type: 'auto',
    description: 'Networks and network services are monitored for cybersecurity events',
    requirements: 'Networks and network services are monitored to find potentially adverse events. Continuous uptime monitoring ensures timely detection of availability issues.',
    recommendations: ['Implement continuous uptime monitoring', 'Set alerting thresholds for response time', 'Monitor at 5-minute intervals or less', 'Investigate anomalies promptly'] },
  { code: 'DE.CM-06', title: 'External Service Provider Monitoring', domain: 'Detect', type: 'auto',
    description: 'External service provider activities are monitored',
    requirements: 'External service provider activities and services are monitored to find potentially adverse events. CDN and SSL certificate providers are tracked for availability and integrity.',
    recommendations: ['Monitor CDN provider status', 'Track SSL certificate issuer changes', 'Verify third-party service SLAs', 'Alert on provider service disruptions'] },
  { code: 'DE.CM-09', title: 'Computing Hardware & Software Monitoring', domain: 'Detect', type: 'auto',
    description: 'Computing hardware and software are monitored for security events',
    requirements: 'Computing hardware, software, runtime environments, and their data are monitored to find potentially adverse events. Technology fingerprinting identifies software changes.',
    recommendations: ['Run technology fingerprinting regularly', 'Monitor for unauthorized software changes', 'Track component version updates', 'Alert on unexpected technology changes'] },
  { code: 'DE.AE-01', title: 'Anomaly Detection', domain: 'Detect', type: 'auto',
    description: 'Anomalies and events are detected and analyzed',
    requirements: 'A baseline of network operations and expected data flows is established and managed. DDoS risk assessment includes anomaly detection for response time spikes and availability flapping.',
    recommendations: ['Establish baselines for normal operation', 'Detect and alert on anomalous behavior', 'Correlate anomalies across multiple data sources', 'Investigate anomalies within defined timeframes'] },

  // RESPOND
  { code: 'RS.RP-01', title: 'Incident Response Planning', domain: 'Respond', type: 'manual',
    description: 'Response plan is executed during or after an incident',
    requirements: 'The response plan is executed during or after a cybersecurity incident. Established procedures guide containment, eradication, and recovery actions.',
    recommendations: ['Maintain incident response playbooks', 'Conduct tabletop exercises quarterly', 'Define escalation procedures', 'Review response plan after each incident'] },
  { code: 'RS.AN-01', title: 'Incident Analysis', domain: 'Respond', type: 'manual',
    description: 'Investigations are conducted to support incident response',
    requirements: 'Investigations are conducted to ensure effective response and support forensics and recovery activities. Root cause analysis is performed for significant incidents.',
    recommendations: ['Establish forensic investigation procedures', 'Preserve evidence during investigations', 'Document findings and lessons learned', 'Share insights with relevant stakeholders'] },
  { code: 'RS.CO-01', title: 'Incident Reporting & Communication', domain: 'Respond', type: 'manual',
    description: 'Activities are coordinated with internal and external stakeholders',
    requirements: 'Response activities are coordinated with internal and external stakeholders as appropriate, including external support from law enforcement agencies.',
    recommendations: ['Define communication protocols for incidents', 'Maintain stakeholder contact lists', 'Report incidents to regulatory bodies as required', 'Coordinate with law enforcement when appropriate'] },

  // RECOVER
  { code: 'RC.RP-01', title: 'Recovery Planning', domain: 'Recover', type: 'manual',
    description: 'Recovery plan is executed during or after an incident',
    requirements: 'The recovery plan is executed during or after a cybersecurity incident. Recovery activities restore systems and assets to normal operations.',
    recommendations: ['Maintain and test recovery plans', 'Define recovery time objectives (RTO)', 'Prioritize recovery of critical systems', 'Document recovery procedures'] },
  { code: 'RC.CO-01', title: 'Recovery Communication', domain: 'Recover', type: 'manual',
    description: 'Restoration activities are coordinated with internal and external parties',
    requirements: 'Restoration activities are coordinated with internal and external parties. Public relations and stakeholder communications support recovery reputation management.',
    recommendations: ['Coordinate recovery with all affected parties', 'Communicate recovery progress to stakeholders', 'Document lessons learned from recovery', 'Update recovery plans based on experience'] },
];

/* ═══════════════════════════════════════════════
   OWASP Top 10 (2021)
   ═══════════════════════════════════════════════ */
const OWASP_CONTROLS: FrameworkControl[] = [
  { code: 'A01:2021', title: 'Broken Access Control', domain: 'App', type: 'hybrid',
    description: 'Access control enforces policy such that users cannot act outside of their intended permissions',
    requirements: 'Access control enforces policy such that users cannot act outside of their intended permissions. X-Frame-Options prevents clickjacking and Content-Security-Policy prevents unauthorized resource loading.',
    recommendations: ['Deploy X-Frame-Options header (DENY or SAMEORIGIN)', 'Implement Content-Security-Policy header', 'Deny access by default, require explicit grants', 'Log and alert on access control failures'] },
  { code: 'A02:2021', title: 'Cryptographic Failures', domain: 'App', type: 'auto',
    description: 'Failures related to cryptography which often lead to sensitive data exposure',
    requirements: 'Cryptographic mechanisms are properly implemented to protect data confidentiality and integrity. Valid SSL/TLS 1.2+ certificates and HSTS headers prevent data exposure and downgrade attacks.',
    recommendations: ['Use TLS 1.2 or higher for all connections', 'Deploy HSTS with long max-age values', 'Use strong cipher suites only', 'Implement certificate transparency monitoring'] },
  { code: 'A03:2021', title: 'Injection', domain: 'App', type: 'hybrid',
    description: 'Application is vulnerable to injection attacks (SQL, XSS, etc.)',
    requirements: 'User-supplied data is validated, filtered, or sanitized. Content-Security-Policy prevents XSS injection, X-Content-Type-Options prevents MIME sniffing, and database ports are not publicly exposed.',
    recommendations: ['Implement Content-Security-Policy header', 'Deploy X-Content-Type-Options: nosniff', 'Close all database ports to public access', 'Use parameterized queries and input validation'] },
  { code: 'A04:2021', title: 'Insecure Design', domain: 'App', type: 'manual',
    description: 'Risks related to design and architectural flaws',
    requirements: 'A secure development lifecycle with threat modeling addresses design and architectural flaws. Secure design patterns and reference architectures are used.',
    recommendations: ['Implement threat modeling in design phase', 'Use secure design patterns and reference architectures', 'Conduct design reviews with security experts', 'Establish a secure development lifecycle (SDLC)'] },
  { code: 'A05:2021', title: 'Security Misconfiguration', domain: 'App', type: 'auto',
    description: 'Application lacks proper security hardening',
    requirements: 'Security hardening is applied across the application stack. Complete security headers are deployed, server version information is hidden, and unnecessary ports are closed.',
    recommendations: ['Deploy all 7 recommended security headers', 'Hide server version information', 'Close all unnecessary ports', 'Conduct regular configuration audits'] },
  { code: 'A06:2021', title: 'Vulnerable & Outdated Components', domain: 'App', type: 'auto',
    description: 'Using components with known vulnerabilities',
    requirements: 'All software components are current and free from known vulnerabilities. Technology fingerprinting identifies outdated software that needs updating.',
    recommendations: ['Inventory all software components and versions', 'Monitor for CVEs in used components', 'Update components to latest stable versions', 'Remove unused or deprecated components'] },
  { code: 'A07:2021', title: 'Identification & Authentication Failures', domain: 'App', type: 'hybrid',
    description: 'Authentication mechanisms fail to protect against brute-force or session attacks',
    requirements: 'Authentication mechanisms prevent brute-force attacks and session hijacking. Rate limiting prevents credential stuffing and HSTS prevents session downgrade attacks.',
    recommendations: ['Implement rate limiting on authentication endpoints', 'Deploy HSTS to prevent session hijacking', 'Enforce multi-factor authentication', 'Implement account lockout policies'] },
  { code: 'A08:2021', title: 'Software & Data Integrity Failures', domain: 'App', type: 'hybrid',
    description: 'Code and infrastructure lack integrity verification',
    requirements: 'Software and data integrity is verified. Content integrity monitoring detects unauthorized modifications and Content-Security-Policy with integrity directives protects against tampering.',
    recommendations: ['Implement defacement/content monitoring', 'Deploy CSP with integrity directives', 'Use signed releases and verified packages', 'Monitor for unauthorized code changes'] },
  { code: 'A09:2021', title: 'Security Logging & Monitoring Failures', domain: 'App', type: 'auto',
    description: 'Insufficient logging and monitoring fails to detect breaches',
    requirements: 'Comprehensive security logging and monitoring detects breaches in a timely manner. All critical systems are monitored with current and active checks across uptime, SSL, DDoS, and early warning systems.',
    recommendations: ['Monitor all critical systems continuously', 'Ensure monitoring checks run on schedule', 'Alert on monitoring gaps or stale checks', 'Retain logs for incident investigation'] },
  { code: 'A10:2021', title: 'Server-Side Request Forgery (SSRF)', domain: 'App', type: 'manual',
    description: 'SSRF flaws occur when a web app fetches remote resources without validating URLs',
    requirements: 'Server-side request forgery is prevented by validating and sanitizing all user-supplied URLs before server-side fetching. Network layer protections limit outbound requests.',
    recommendations: ['Validate and sanitize all user-supplied URLs', 'Implement allowlists for outbound requests', 'Use network segmentation to limit SSRF impact', 'Monitor for unusual outbound connection patterns'] },
];

/* ═══════════════════════════════════════════════
   ITU National Cybersecurity Index
   ═══════════════════════════════════════════════ */
const ITU_CONTROLS: FrameworkControl[] = [
  // LEGAL MEASURES
  { code: 'ITU-L1', title: 'Cybercrime Legislation', domain: 'Legal', type: 'manual',
    description: 'Does the country have substantive cybercrime laws?',
    requirements: 'The country has enacted substantive and procedural cybercrime legislation that criminalizes cyberattacks and provides legal frameworks for prosecution.',
    recommendations: ['Enact comprehensive cybercrime legislation', 'Align laws with Budapest Convention standards', 'Include provisions for electronic evidence', 'Establish penalties proportionate to offenses'] },
  { code: 'ITU-L2', title: 'Cybersecurity Regulation', domain: 'Legal', type: 'manual',
    description: 'Does the country have cybersecurity regulations for critical infrastructure?',
    requirements: 'Cybersecurity regulations are established for critical infrastructure sectors including government, telecommunications, banking, and health.',
    recommendations: ['Develop sector-specific cybersecurity regulations', 'Mandate minimum security standards for critical infrastructure', 'Establish regulatory oversight and compliance mechanisms', 'Create incident reporting requirements'] },
  { code: 'ITU-L3', title: 'Data Protection Legislation', domain: 'Legal', type: 'manual',
    description: 'Does the country have data protection/privacy laws?',
    requirements: 'Data protection and privacy legislation protects personal data of citizens and establishes rights for data subjects and obligations for data controllers.',
    recommendations: ['Enact comprehensive data protection legislation', 'Establish a data protection authority', 'Define data subject rights (access, deletion, portability)', 'Mandate data breach notification requirements'] },

  // TECHNICAL MEASURES
  { code: 'ITU-T1', title: 'National CERT/CIRT', domain: 'Technical', type: 'hybrid',
    description: 'Does the country have a functioning national CERT?',
    requirements: 'The country has established a functioning national Computer Emergency Response Team (CERT) with active monitoring capabilities across multiple organizations and sectors.',
    recommendations: ['Establish 24/7 CERT operations center', 'Monitor 15+ critical organizations', 'Implement multi-layer security monitoring', 'Develop incident coordination capabilities'] },
  { code: 'ITU-T2', title: 'National Cybersecurity Standards', domain: 'Technical', type: 'hybrid',
    description: 'Are cybersecurity standards implemented?',
    requirements: 'Nationally or internationally recognized cybersecurity standards (CIS Controls, NIST CSF) are adopted and compliance is assessed across organizations.',
    recommendations: ['Adopt internationally recognized cybersecurity frameworks', 'Conduct compliance assessments across organizations', 'Set compliance score targets above 70%', 'Provide guidance and tools for compliance'] },
  { code: 'ITU-T3', title: 'Child Online Protection', domain: 'Technical', type: 'manual',
    description: 'Are there technical measures to protect children online?',
    requirements: 'Technical measures are in place to protect children online, including content filtering, age verification, and online safety education programs.',
    recommendations: ['Implement content filtering for harmful material', 'Develop age verification mechanisms', 'Create online safety education programs', 'Establish reporting mechanisms for abuse'] },
  { code: 'ITU-T4', title: 'Government Website Security', domain: 'Technical', type: 'auto',
    description: 'Are government websites secured with HTTPS?',
    requirements: 'All government websites are secured with valid HTTPS/SSL certificates, ensuring encrypted communications for all citizen-facing services.',
    recommendations: ['Deploy valid SSL certificates on all government websites', 'Implement automatic certificate renewal', 'Monitor for certificate expiration', 'Enforce HTTPS-only access'] },
  { code: 'ITU-T5', title: 'DDoS Protection', domain: 'Technical', type: 'auto',
    description: 'Are critical websites protected against DDoS attacks?',
    requirements: 'Critical national websites are protected against DDoS attacks through CDN deployment, traffic filtering, and capacity management.',
    recommendations: ['Deploy CDN protection on critical websites', 'Implement WAF for application-layer attacks', 'Establish DDoS response procedures', 'Conduct DDoS resilience testing'] },
  { code: 'ITU-T6', title: 'National Email Authentication', domain: 'Technical', type: 'auto',
    description: 'Do government domains have email authentication (SPF, DMARC)?',
    requirements: 'Government domains implement email authentication standards (SPF, DKIM, DMARC) to prevent email spoofing and phishing attacks targeting citizens.',
    recommendations: ['Deploy SPF records on all government domains', 'Implement DMARC with enforcement policies', 'Enable DKIM signing for all outbound email', 'Monitor and report on email authentication compliance'] },
  { code: 'ITU-T7', title: 'Vulnerability Management', domain: 'Technical', type: 'auto',
    description: 'Is there a national vulnerability management process?',
    requirements: 'A national vulnerability management process identifies, assesses, and remediates vulnerabilities across government and critical infrastructure organizations.',
    recommendations: ['Scan organizations for outdated software regularly', 'Consume and act on threat intelligence feeds', 'Track vulnerability remediation across sectors', 'Share vulnerability advisories with stakeholders'] },

  // ORGANIZATIONAL MEASURES
  { code: 'ITU-O1', title: 'National Cybersecurity Strategy', domain: 'Organizational', type: 'manual',
    description: 'Does the country have a published national cybersecurity strategy?',
    requirements: 'A national cybersecurity strategy has been published, setting out the country\'s approach to cybersecurity including objectives, priorities, and responsibilities.',
    recommendations: ['Develop and publish national cybersecurity strategy', 'Set measurable objectives and timelines', 'Assign clear roles and responsibilities', 'Review and update strategy every 3-5 years'] },
  { code: 'ITU-O2', title: 'National Cybersecurity Agency', domain: 'Organizational', type: 'manual',
    description: 'Is there a dedicated government agency for cybersecurity?',
    requirements: 'A dedicated government agency or authority is responsible for cybersecurity coordination, policy development, and national incident response.',
    recommendations: ['Establish a national cybersecurity authority', 'Define clear mandate and authority', 'Ensure adequate staffing and budget', 'Coordinate across government departments'] },
  { code: 'ITU-O3', title: 'Cybersecurity Metrics & Benchmarks', domain: 'Organizational', type: 'hybrid',
    description: 'Are cybersecurity metrics and benchmarks established?',
    requirements: 'Cybersecurity metrics and benchmarks are established and tracked to measure the country\'s cybersecurity posture and progress over time.',
    recommendations: ['Define key cybersecurity performance indicators', 'Calculate security scores for all organizations', 'Track metrics over time for trend analysis', 'Benchmark against regional and global standards'] },

  // CAPACITY BUILDING
  { code: 'ITU-CB1', title: 'Public Awareness Campaigns', domain: 'Capacity', type: 'manual',
    description: 'Are there government-led cybersecurity awareness programs?',
    requirements: 'The government conducts public cybersecurity awareness campaigns to educate citizens about online threats and safe online practices.',
    recommendations: ['Launch national cybersecurity awareness campaigns', 'Partner with media for public education', 'Create multilingual awareness materials', 'Measure campaign reach and effectiveness'] },
  { code: 'ITU-CB2', title: 'Cybersecurity Education', domain: 'Capacity', type: 'manual',
    description: 'Are there cybersecurity education programs?',
    requirements: 'Cybersecurity education programs exist at university and vocational levels, producing qualified cybersecurity professionals for the workforce.',
    recommendations: ['Establish cybersecurity degree programs', 'Develop vocational training pathways', 'Create scholarship programs for cybersecurity students', 'Partner with industry for practical training'] },
  { code: 'ITU-CB3', title: 'Government Staff Training', domain: 'Capacity', type: 'manual',
    description: 'Do government employees receive cybersecurity training?',
    requirements: 'Government employees receive regular cybersecurity training appropriate to their roles, including awareness training and specialized technical training.',
    recommendations: ['Mandate cybersecurity training for all government staff', 'Provide specialized training for IT personnel', 'Conduct regular training refreshers', 'Track and report training completion rates'] },
  { code: 'ITU-CB4', title: 'Cybersecurity R&D', domain: 'Capacity', type: 'manual',
    description: 'Is there investment in cybersecurity R&D?',
    requirements: 'The country invests in cybersecurity research and development through academic institutions, government programs, or public-private partnerships.',
    recommendations: ['Fund cybersecurity research programs', 'Establish research partnerships with universities', 'Support cybersecurity innovation and startups', 'Publish and share research findings'] },

  // COOPERATION
  { code: 'ITU-CO1', title: 'International Agreements', domain: 'Cooperation', type: 'manual',
    description: 'Is the country party to international cybersecurity treaties?',
    requirements: 'The country is party to international cybersecurity agreements and treaties such as the Budapest Convention or African Union Malabo Convention.',
    recommendations: ['Ratify Budapest Convention on Cybercrime', 'Join African Union Malabo Convention', 'Participate in bilateral cybersecurity agreements', 'Engage in multilateral cybersecurity dialogues'] },
  { code: 'ITU-CO2', title: 'Public-Private Partnerships', domain: 'Cooperation', type: 'hybrid',
    description: 'Are there partnerships between government and private sector?',
    requirements: 'Partnerships exist between government and private sector for cybersecurity, with both sectors contributing to and benefiting from shared cybersecurity monitoring and intelligence.',
    recommendations: ['Establish formal public-private partnership frameworks', 'Include private sector in national cybersecurity monitoring', 'Share threat intelligence between sectors', 'Conduct joint cybersecurity exercises'] },
  { code: 'ITU-CO3', title: 'Inter-Agency Cooperation', domain: 'Cooperation', type: 'manual',
    description: 'Is there coordination between government agencies on cybersecurity?',
    requirements: 'Government agencies coordinate on cybersecurity matters through formal mechanisms, including information sharing, joint operations, and coordinated incident response.',
    recommendations: ['Establish inter-agency cybersecurity coordination mechanisms', 'Define information sharing protocols', 'Conduct joint training and exercises', 'Create shared situational awareness platforms'] },
  { code: 'ITU-CO4', title: 'International CERT Cooperation', domain: 'Cooperation', type: 'manual',
    description: 'Does the national CERT participate in international CERT networks?',
    requirements: 'The national CERT participates in international CERT networks (FIRST, AfricaCERT) for information sharing, capacity building, and coordinated incident response.',
    recommendations: ['Apply for FIRST membership', 'Join AfricaCERT and regional networks', 'Participate in international cyber exercises', 'Contribute to global threat intelligence sharing'] },
];

/* ═══════════════════════════════════════════════
   Framework Registry
   ═══════════════════════════════════════════════ */
export const FRAMEWORKS: ComplianceFramework[] = [
  { key: 'cis-v8', name: 'CIS Controls v8', domains: ['all', 'Identity', 'Endpoint', 'Backup', 'Network', 'App', 'IR', 'Data'], controls: CIS_CONTROLS },
  { key: 'nist-csf-2', name: 'NIST CSF 2.0', domains: ['all', 'Govern', 'Identify', 'Protect', 'Detect', 'Respond', 'Recover'], controls: NIST_CONTROLS },
  { key: 'owasp-2021', name: 'OWASP Top 10 (2021)', domains: ['all', 'App'], controls: OWASP_CONTROLS },
  { key: 'itu-nci', name: 'ITU National Cybersecurity Index', domains: ['all', 'Legal', 'Technical', 'Organizational', 'Capacity', 'Cooperation'], controls: ITU_CONTROLS },
];

export function getFramework(key: string): ComplianceFramework | undefined {
  return FRAMEWORKS.find(f => f.key === key);
}
